[server]
headless = true
runOnSave = true
fileWatcherType = "poll"

[theme]
base="dark"
#primaryColor="#f63366"
primaryColor="#4082de"
backgroundColor="#0A1222"
secondaryBackgroundColor="#262730"
textColor="#F27522"
font="monospace"